# 应用配置文件
[app]
name = "phone_data"
version = "0.1.0"

[server]
host = "0.0.0.0"
port = 8088
workers = 0      # 0 = auto (num_cpus)

[database]
path = "phone.dat"

[cache]
enabled = true
max_size = 1000

[logging]
level = "info"
format = "json" # "json" or "pretty"
